# Generated by Django 4.2.7 on 2025-07-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Ürünün ekiliş tarihi', null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='bitis_tarihi',
            field=models.DateField(blank=True, help_text='Ürünün hasat tarihi', null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
