# Generated by Django 4.2.7 on 2025-06-25 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='agustos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ağustos Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='aralik',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aralık Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ekim',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ekim Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='eylul',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eylül Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='haziran',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Haziran Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kasim',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kasım Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='mart',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mart Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='mayis',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mayıs Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='nisan',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nisan Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='ocak',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ocak Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='subat',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Şubat Katsayısı'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='temmuz',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Temmuz Katsayısı'),
        ),
    ]
